version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gt_explorer_postgres
    environment:
      POSTGRES_USER: gt_user
      POSTGRES_PASSWORD: gt_password
      POSTGRES_DB: gt_explorer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: